name: Lint

on:
  push:
    branches-ignore:
      - main

jobs:
  lint:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Lint
        run: |
          yarn install
          yarn lint
